#pragma once

#include "driver/adc_types_legacy.h"
#include "driver/gpio.h"
#include "driver/ledc.h"

#define THERMAL_NTC_ADC_UNIT ADC_UNIT_1
#define THERMAL_NTC_ADC_CHANNEL ADC_CHANNEL_0
#define THERMAL_NTC_ADC_ATTEN ADC_ATTEN_DB_12
#define THERMAL_NTC_ADC_BITWIDTH ADC_BITWIDTH_DEFAULT

#define THERMAL_PWM_GPIO GPIO_NUM_4
#define THERMAL_PWM_TIMER LEDC_TIMER_0
#define THERMAL_PWM_MODE LEDC_LOW_SPEED_MODE
#define THERMAL_PWM_CHANNEL LEDC_CHANNEL_0
#define THERMAL_PWM_DUTY_RES LEDC_TIMER_10_BIT
#define THERMAL_PWM_FREQUENCY_HZ (1000U)

#define THERMAL_CONTROL_PERIOD_MS (100U)

#define THERMAL_DEFAULT_SETPOINT_C (37.0f)
